project_id = "myxvxponlmulnjstbjwd"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://497b2947-e810-4aeb-9ce8-108410eaf186.lovableproject.com/**", "https://grc-nexus-ai.lovable.app/**", "https://id-preview--497b2947-e810-4aeb-9ce8-108410eaf186.lovable.app/**", "https://preview--grc-nexus-ai.lovable.app/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400
