-- Seed data para Templates de Riscos - PostgreSQL/Supabase
-- Executar após criar as tabelas do schema

-- Inserir templates de riscos de alta qualidade
INSERT INTO risk_templates (
    id, name, description, category, industry, risk_level, probability, impact, 
    methodology, usage_count, rating, is_popular, created_by, alex_risk_suggested, total_ratings
) VALUES 
-- CATEGORIA: TECNOLÓGICO
(
    'tech-001',
    'Ataque de Ransomware Avançado',
    'Risco de sequestro de dados por malware sofisticado com demanda de resgate financeiro e ameaças de vazamento',
    'Tecnológico',
    'Geral',
    'Muito Alto',
    4,
    5,
    'NIST Cybersecurity Framework',
    2847,
    4.9,
    true,
    'Alex Risk IA',
    true,
    847
),
(
    'tech-002',
    'Vazamento de Dados Pessoais (LGPD)',
    'Exposição não autorizada de informações pessoais de clientes, colaboradores ou terceiros',
    'Tecnológico',
    'Geral',
    'Alto',
    3,
    5,
    'ISO 27001 / Privacy by Design',
    1923,
    4.7,
    true,
    'Especialista LGPD',
    true,
    623
),
(
    'tech-003',
    'Ataque DDoS (Negação de Serviço)',
    'Sobrecarga intencional de sistemas para torná-los indisponíveis aos usuários legítimos',
    'Tecnológico',
    'Tecnologia',
    'Alto',
    3,
    4,
    'NIST Cybersecurity Framework',
    892,
    4.4,
    false,
    'Especialista Segurança',
    true,
    289
),
(
    'tech-004',
    'Vulnerabilidades de Software',
    'Falhas de segurança em aplicações que podem ser exploradas por atacantes',
    'Tecnológico',
    'Geral',
    'Alto',
    4,
    4,
    'OWASP Top 10',
    1456,
    4.5,
    true,
    'DevSecOps Lead',
    true,
    356
),
(
    'tech-005',
    'Falha de Sistema Crítico',
    'Indisponibilidade de sistemas essenciais para operação do negócio',
    'Tecnológico',
    'Geral',
    'Alto',
    3,
    4,
    'ITIL v4',
    1654,
    4.6,
    true,
    'Arquiteto de TI',
    false,
    454
),

-- CATEGORIA: OPERACIONAL
(
    'op-001',
    'Falha na Cadeia de Suprimentos',
    'Interrupção no fornecimento de materiais, serviços ou componentes críticos para operação',
    'Operacional',
    'Manufatura',
    'Alto',
    3,
    4,
    'ISO 31000 / Supply Chain Risk Management',
    1789,
    4.6,
    true,
    'Gerente Supply Chain',
    false,
    489
),
(
    'op-002',
    'Erro Humano em Processos Críticos',
    'Falhas operacionais causadas por erro humano em atividades essenciais do negócio',
    'Operacional',
    'Geral',
    'Médio',
    4,
    3,
    'Human Factors Analysis / Lean Six Sigma',
    2156,
    4.3,
    true,
    'Especialista Qualidade',
    true,
    656
),
(
    'op-003',
    'Falha de Equipamentos Críticos',
    'Quebra ou mau funcionamento de equipamentos essenciais para produção',
    'Operacional',
    'Manufatura',
    'Alto',
    3,
    4,
    'RCM (Reliability Centered Maintenance)',
    1234,
    4.4,
    false,
    'Engenheiro Manutenção',
    false,
    334
),
(
    'op-004',
    'Perda de Pessoal Chave',
    'Saída inesperada de colaboradores críticos para operação',
    'Operacional',
    'Geral',
    'Médio',
    3,
    3,
    'Gestão de Talentos / Succession Planning',
    987,
    4.2,
    false,
    'RH Estratégico',
    true,
    287
),
(
    'op-005',
    'Interrupção de Serviços Terceirizados',
    'Falha ou descontinuidade de serviços críticos prestados por terceiros',
    'Operacional',
    'Geral',
    'Alto',
    2,
    4,
    'Gestão de Terceiros / SLA Management',
    1345,
    4.3,
    true,
    'Gerente Contratos',
    false,
    445
),

-- CATEGORIA: FINANCEIRO
(
    'fin-001',
    'Risco de Liquidez Corporativa',
    'Insuficiência de recursos financeiros líquidos para honrar compromissos de curto prazo',
    'Financeiro',
    'Financeiro',
    'Alto',
    3,
    4,
    'Basel III / IFRS 9',
    1567,
    4.5,
    true,
    'CFO',
    false,
    467
),
(
    'fin-002',
    'Risco de Crédito e Inadimplência',
    'Possibilidade de perdas financeiras devido ao não pagamento de clientes ou contrapartes',
    'Financeiro',
    'Financeiro',
    'Alto',
    3,
    4,
    'Basel III / IFRS 9',
    1890,
    4.6,
    true,
    'Gerente Crédito',
    true,
    590
),
(
    'fin-003',
    'Risco de Mercado e Câmbio',
    'Perdas decorrentes de variações adversas em taxas de juros, câmbio ou preços de commodities',
    'Financeiro',
    'Financeiro',
    'Alto',
    4,
    3,
    'VaR (Value at Risk) / Basel III',
    1123,
    4.4,
    false,
    'Tesoureiro',
    false,
    323
),
(
    'fin-004',
    'Fraude Financeira',
    'Atos fraudulentos que resultem em perdas financeiras para organização',
    'Financeiro',
    'Geral',
    'Alto',
    2,
    5,
    'COSO Fraud Risk Management',
    876,
    4.7,
    false,
    'Auditoria Interna',
    true,
    276
),
(
    'fin-005',
    'Risco de Concentração',
    'Exposição excessiva a um único cliente, fornecedor ou mercado',
    'Financeiro',
    'Geral',
    'Médio',
    3,
    3,
    'Análise de Concentração / Diversificação',
    654,
    4.1,
    false,
    'Analista Risco',
    false,
    154
),

-- CATEGORIA: REGULATÓRIO
(
    'reg-001',
    'Não Conformidade LGPD/GDPR',
    'Violação das normas de proteção de dados pessoais estabelecidas pela LGPD e GDPR',
    'Regulatório',
    'Geral',
    'Alto',
    3,
    4,
    'Privacy by Design / ISO 27701',
    2234,
    4.7,
    true,
    'DPO',
    true,
    734
),
(
    'reg-002',
    'Não Conformidade Trabalhista',
    'Violação de normas trabalhistas e previdenciárias',
    'Regulatório',
    'Geral',
    'Alto',
    3,
    4,
    'CLT / Normas Regulamentadoras',
    1456,
    4.3,
    true,
    'Jurídico Trabalhista',
    false,
    456
),
(
    'reg-003',
    'Não Conformidade Ambiental',
    'Violação de normas ambientais e licenças operacionais',
    'Regulatório',
    'Manufatura',
    'Alto',
    2,
    5,
    'ISO 14001 / Licenciamento Ambiental',
    987,
    4.5,
    false,
    'Especialista Ambiental',
    true,
    287
),
(
    'reg-004',
    'Não Conformidade Fiscal',
    'Violação de obrigações tributárias e fiscais',
    'Regulatório',
    'Geral',
    'Alto',
    3,
    4,
    'Planejamento Tributário / Compliance Fiscal',
    1789,
    4.4,
    true,
    'Controller',
    false,
    589
),
(
    'reg-005',
    'Não Conformidade Setorial',
    'Violação de normas específicas do setor de atuação',
    'Regulatório',
    'Geral',
    'Médio',
    2,
    4,
    'Normas Setoriais Específicas',
    876,
    4.2,
    false,
    'Compliance Officer',
    true,
    276
),

-- CATEGORIA: REPUTACIONAL
(
    'rep-001',
    'Crise de Reputação Digital',
    'Danos à imagem da organização através de mídias sociais e canais digitais',
    'Reputacional',
    'Geral',
    'Alto',
    3,
    4,
    'Crisis Management Framework',
    1456,
    4.3,
    true,
    'Diretor Marketing',
    true,
    456
),
(
    'rep-002',
    'Escândalo Corporativo ou Ético',
    'Exposição pública de condutas inadequadas, corrupção ou violações éticas',
    'Reputacional',
    'Geral',
    'Muito Alto',
    2,
    5,
    'Compliance & Ethics Framework',
    789,
    4.8,
    false,
    'Chief Compliance Officer',
    true,
    289
),
(
    'rep-003',
    'Recall de Produtos',
    'Necessidade de recolhimento de produtos por defeitos ou riscos à segurança',
    'Reputacional',
    'Manufatura',
    'Alto',
    2,
    4,
    'Gestão de Qualidade / ISO 9001',
    567,
    4.4,
    false,
    'Gerente Qualidade',
    false,
    167
),
(
    'rep-004',
    'Discriminação e Assédio',
    'Casos de discriminação, assédio moral ou sexual no ambiente de trabalho',
    'Reputacional',
    'Geral',
    'Alto',
    2,
    4,
    'Políticas de Diversidade e Inclusão',
    432,
    4.6,
    false,
    'RH Estratégico',
    true,
    132
),
(
    'rep-005',
    'Acidentes de Trabalho Graves',
    'Acidentes que resultem em lesões graves ou óbito de colaboradores',
    'Reputacional',
    'Manufatura',
    'Muito Alto',
    1,
    5,
    'Segurança do Trabalho / OHSAS 18001',
    234,
    4.9,
    false,
    'Engenheiro Segurança',
    false,
    134
);

-- Inserir controles para os templates
INSERT INTO risk_template_controls (template_id, control_description, control_order) VALUES
-- Controles para Ransomware (tech-001)
('tech-001', 'Backup automatizado diário com teste de restauração', 1),
('tech-001', 'Treinamento anti-phishing para colaboradores', 2),
('tech-001', 'Segmentação de rede e microsegmentação', 3),
('tech-001', 'Monitoramento 24/7 com SOC especializado', 4),
('tech-001', 'Políticas de acesso privilegiado (PAM)', 5),
('tech-001', 'Atualizações de segurança automatizadas', 6),

-- Controles para Vazamento LGPD (tech-002)
('tech-002', 'Criptografia de dados em trânsito e repouso', 1),
('tech-002', 'Controle de acesso baseado em funções (RBAC)', 2),
('tech-002', 'Monitoramento de atividades privilegiadas', 3),
('tech-002', 'Classificação e rotulação de dados sensíveis', 4),
('tech-002', 'DLP (Data Loss Prevention)', 5),
('tech-002', 'Auditoria regular de acessos e permissões', 6),

-- Controles para DDoS (tech-003)
('tech-003', 'Proteção DDoS em nuvem (CDN)', 1),
('tech-003', 'Balanceamento de carga inteligente', 2),
('tech-003', 'Rate limiting e throttling', 3),
('tech-003', 'Monitoramento de tráfego anômalo em tempo real', 4),
('tech-003', 'Plano de resposta a incidentes DDoS', 5),
('tech-003', 'Parcerias com provedores de mitigação', 6);

-- Inserir KRIs para os templates
INSERT INTO risk_template_kris (template_id, kri_description, kri_order) VALUES
-- KRIs para Ransomware (tech-001)
('tech-001', 'Tentativas de phishing detectadas por mês', 1),
('tech-001', 'Tempo médio de resposta a incidentes (MTTR)', 2),
('tech-001', 'Taxa de sucesso de backup e restauração', 3),
('tech-001', 'Número de vulnerabilidades críticas não corrigidas', 4),

-- KRIs para Vazamento LGPD (tech-002)
('tech-002', 'Número de incidentes de vazamento por trimestre', 1),
('tech-002', 'Tempo para detecção de vazamentos', 2),
('tech-002', 'Percentual de dados pessoais criptografados', 3),
('tech-002', 'Número de acessos não autorizados detectados', 4),

-- KRIs para DDoS (tech-003)
('tech-003', 'Volume de tráfego anômalo detectado', 1),
('tech-003', 'Tempo de mitigação de ataques DDoS', 2),
('tech-003', 'Disponibilidade durante ataques (%)', 3),
('tech-003', 'Número de ataques DDoS por mês', 4);

-- Inserir tags para os templates
INSERT INTO risk_template_tags (template_id, tag) VALUES
-- Tags para Ransomware (tech-001)
('tech-001', 'cibersegurança'),
('tech-001', 'malware'),
('tech-001', 'backup'),
('tech-001', 'crítico'),
('tech-001', 'soc'),

-- Tags para Vazamento LGPD (tech-002)
('tech-002', 'lgpd'),
('tech-002', 'privacidade'),
('tech-002', 'criptografia'),
('tech-002', 'dlp'),
('tech-002', 'anpd'),

-- Tags para DDoS (tech-003)
('tech-003', 'ddos'),
('tech-003', 'disponibilidade'),
('tech-003', 'cdn'),
('tech-003', 'mitigação');

-- Inserir algumas avaliações de exemplo
INSERT INTO risk_template_ratings (template_id, user_id, rating) VALUES
('tech-001', 'user-001', 5),
('tech-001', 'user-002', 5),
('tech-001', 'user-003', 4),
('tech-001', 'user-004', 5),
('tech-002', 'user-001', 5),
('tech-002', 'user-002', 4),
('tech-002', 'user-003', 5),
('tech-003', 'user-001', 4),
('tech-003', 'user-002', 4),
('tech-003', 'user-003', 5);

-- Comentário final
COMMENT ON TABLE risk_templates IS 'Biblioteca completa com 25 templates de riscos de alta qualidade distribuídos em 5 categorias principais';
"