-- =====================================================
-- DADOS DE TESTE ROBUSTOS PARA MÓDULO DE LGPD
-- =====================================================
-- Este script popula o banco com dados de teste abrangentes
-- para todas as funcionalidades do módulo de privacidade

-- Bases Legais (múltiplas bases para diferentes cenários)
INSERT INTO legal_bases (
  id, name, description, legal_basis_type, legal_article, justification,
  applies_to_categories, applies_to_processing, valid_from, valid_until,
  status, legal_responsible_id, created_by
) VALUES 
  (
    gen_random_uuid(),
    'Consentimento para Marketing',
    'Base legal para campanhas de marketing e comunicação comercial',
    'consentimento',
    'Art. 7º, I da LGPD',
    'O titular forneceu consentimento livre, informado e inequívoco para receber comunicações comerciais',
    ARRAY['contato', 'comportamental', 'profissional'],
    ARRAY['marketing', 'comunicacao_comercial', 'analise_comportamental'],
    NOW(),
    NOW() + INTERVAL '2 years',
    'active',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Execução de Contrato - Funcionários',
    'Tratamento de dados pessoais de funcionários para execução do contrato de trabalho',
    'contrato',
    'Art. 7º, V da LGPD',
    'Dados necessários para execução de contrato do qual o titular é parte',
    ARRAY['identificacao', 'contato', 'profissional', 'financeiro'],
    ARRAY['gestao_rh', 'folha_pagamento', 'controle_acesso'],
    NOW(),
    NULL,
    'active',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Obrigação Legal - Retenção Fiscal',
    'Retenção de dados para cumprimento de obrigações fiscais',
    'obrigacao_legal',
    'Art. 7º, II da LGPD',
    'Cumprimento de obrigação legal pela Receita Federal - prazo de 5 anos',
    ARRAY['identificacao', 'financeiro'],
    ARRAY['contabilidade', 'declaracoes_fiscais'],
    NOW(),
    NOW() + INTERVAL '5 years',
    'active',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Interesse Legítimo - Segurança',
    'Monitoramento de segurança das instalações e sistemas',
    'interesse_legitimo',
    'Art. 7º, IX da LGPD',
    'Proteção do patrimônio e segurança das pessoas nas dependências da empresa',
    ARRAY['identificacao', 'localizacao', 'biometrico'],
    ARRAY['videomonitoramento', 'controle_acesso', 'seguranca'],
    NOW(),
    NOW() + INTERVAL '1 year',
    'active',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1)
  );

-- Consentimentos (diversos cenários e status)
INSERT INTO consents (
  id, data_subject_email, data_subject_name, data_subject_document,
  purpose, data_categories, legal_basis_id, status, granted_at,
  revoked_at, expired_at, collection_method, collection_source,
  evidence_url, is_informed, is_specific, is_free, is_unambiguous,
  privacy_policy_version, language, created_by
) VALUES 
  (
    gen_random_uuid(),
    'joao.silva@email.com',
    'João Silva Santos',
    '12345678901',
    'Recebimento de newsletters e ofertas promocionais',
    ARRAY['contato', 'comportamental'],
    (SELECT id FROM legal_bases WHERE legal_basis_type = 'consentimento' LIMIT 1),
    'granted',
    NOW() - INTERVAL '30 days',
    NULL,
    NOW() + INTERVAL '2 years',
    'website_form',
    'https://empresa.com/newsletter-signup',
    'https://empresa.com/evidences/consent-123456.pdf',
    true,
    true,
    true,
    true,
    '2.1',
    'pt-BR',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'maria.santos@email.com',
    'Maria Santos Oliveira',
    '98765432109',
    'Análise de perfil para ofertas personalizadas',
    ARRAY['comportamental', 'profissional', 'financeiro'],
    (SELECT id FROM legal_bases WHERE legal_basis_type = 'consentimento' LIMIT 1),
    'revoked',
    NOW() - INTERVAL '90 days',
    NOW() - INTERVAL '15 days',
    NULL,
    'mobile_app',
    'App Mobile v3.2',
    'https://empresa.com/evidences/consent-789012.pdf',
    true,
    true,
    true,
    true,
    '2.0',
    'pt-BR',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'carlos.oliveira@email.com',
    'Carlos Oliveira Costa',
    '11122233344',
    'Comunicação sobre serviços contratados',
    ARRAY['contato'],
    (SELECT id FROM legal_bases WHERE legal_basis_type = 'consentimento' LIMIT 1),
    'expired',
    NOW() - INTERVAL '400 days',
    NULL,
    NOW() - INTERVAL '30 days',
    'phone_call',
    'Central de Atendimento',
    NULL,
    true,
    true,
    true,
    true,
    '1.5',
    'pt-BR',
    (SELECT id FROM auth.users LIMIT 1)
  );

-- Solicitações de Titulares (diversos tipos e status)
INSERT INTO data_subject_requests (
  id, requester_name, requester_email, requester_document, requester_phone,
  request_type, request_description, specific_data_requested, data_categories,
  identity_verified, verification_method, verification_documents,
  verified_by, verified_at, status, assigned_to, due_date, response,
  response_method, response_attachments, responded_at, responded_by,
  internal_notes, escalated, escalated_to, escalated_at, escalation_reason,
  received_at, created_by
) VALUES 
  (
    gen_random_uuid(),
    'Ana Paula Ferreira',
    'ana.ferreira@email.com',
    '55566677788',
    '(11) 99988-7766',
    'acesso',
    'Solicito acesso a todos os meus dados pessoais tratados pela empresa, incluindo dados de cadastro, histórico de compras e preferências',
    'Dados de cadastro, histórico transacional, preferências de produto',
    ARRAY['identificacao', 'contato', 'financeiro', 'comportamental'],
    true,
    'document_upload',
    ARRAY['rg-frente.pdf', 'rg-verso.pdf'],
    (SELECT id FROM auth.users LIMIT 1),
    NOW() - INTERVAL '2 days',
    'in_progress',
    (SELECT id FROM auth.users LIMIT 1),
    NOW() + INTERVAL '10 days',
    NULL,
    'email',
    NULL,
    NULL,
    NULL,
    'Solicitação complexa - requer consulta a múltiplos sistemas',
    false,
    NULL,
    NULL,
    NULL,
    NOW() - INTERVAL '5 days',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Roberto Machado Silva',
    'roberto.machado@email.com',
    '99988877766',
    NULL,
    'eliminacao',
    'Solicito a eliminação completa de todos os meus dados pessoais, pois não tenho mais interesse nos serviços da empresa',
    'Todos os dados pessoais',
    ARRAY['identificacao', 'contato', 'comportamental', 'profissional'],
    true,
    'email_confirmation',
    NULL,
    (SELECT id FROM auth.users LIMIT 1),
    NOW() - INTERVAL '1 day',
    'completed',
    (SELECT id FROM auth.users LIMIT 1),
    NOW() + INTERVAL '12 days',
    'Seus dados foram eliminados conforme solicitado. Apenas dados com obrigação legal de retenção foram mantidos (dados fiscais por 5 anos conforme legislação). Você receberá confirmação por escrito.',
    'email',
    ARRAY['comprovante-eliminacao.pdf', 'dados-retidos-obrigacao-legal.pdf'],
    NOW() - INTERVAL '6 hours',
    (SELECT id FROM auth.users LIMIT 1),
    'Eliminação realizada com sucesso. Mantidos apenas dados com base em obrigação legal.',
    false,
    NULL,
    NULL,
    NULL,
    NOW() - INTERVAL '8 days',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Luciana Costa Pereira',
    'luciana.costa@email.com',
    '12312312312',
    '(21) 98765-4321',
    'correcao',
    'Meu endereço e telefone estão desatualizados no sistema. Solicito a correção dessas informações',
    'Endereço residencial e telefone de contato',
    ARRAY['contato', 'localizacao'],
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'under_verification',
    NULL,
    NOW() + INTERVAL '13 days',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Aguardando documentos para verificação de identidade',
    false,
    NULL,
    NULL,
    NULL,
    NOW() - INTERVAL '2 days',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Pedro Henrique Santos',
    'pedro.santos@email.com',
    '45645645645',
    '(31) 99999-8888',
    'portabilidade',
    'Solicito a portabilidade dos meus dados para transferir para outra empresa. Preciso dos dados em formato estruturado',
    'Histórico de compras, preferências, dados de cadastro',
    ARRAY['identificacao', 'contato', 'comportamental', 'financeiro'],
    true,
    'video_call',
    ARRAY['ata-videochamada-verificacao.pdf'],
    (SELECT id FROM auth.users LIMIT 1),
    NOW() - INTERVAL '3 hours',
    'escalated',
    (SELECT id FROM auth.users LIMIT 1),
    NOW() + INTERVAL '11 days',
    NULL,
    'portal',
    NULL,
    NULL,
    NULL,
    'Escalado para time jurídico - requer análise de viabilidade técnica para portabilidade',
    true,
    (SELECT id FROM auth.users LIMIT 1),
    NOW() - INTERVAL '1 hour',
    'Complexidade técnica para extração e formatação dos dados requer análise especializada',
    NOW() - INTERVAL '6 days',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Isabella Rodrigues Lima',
    'isabella.rodrigues@email.com',
    '78978978978',
    NULL,
    'revogacao_consentimento',
    'Revogo meu consentimento para recebimento de comunicações de marketing e análise de perfil',
    'Consentimentos para marketing e perfilização',
    ARRAY['contato', 'comportamental'],
    true,
    'document_upload',
    ARRAY['documento-identidade.pdf'],
    (SELECT id FROM auth.users LIMIT 1),
    NOW() - INTERVAL '4 hours',
    'completed',
    (SELECT id FROM auth.users LIMIT 1),
    NOW() + INTERVAL '11 days',
    'Seu consentimento foi revogado com sucesso. Você não receberá mais comunicações de marketing e seus dados não serão mais utilizados para análise comportamental.',
    'email',
    ARRAY['comprovante-revogacao-consentimento.pdf'],
    NOW() - INTERVAL '2 hours',
    (SELECT id FROM auth.users LIMIT 1),
    'Revogação processada e sistemas atualizados',
    false,
    NULL,
    NULL,
    NULL,
    NOW() - INTERVAL '1 day',
    (SELECT id FROM auth.users LIMIT 1)
  );

-- Inventário de Dados (itens detalhados)
INSERT INTO data_inventory (
  id, name, description, data_category, data_types, system_name,
  database_name, table_field_names, file_locations, estimated_volume,
  retention_period_months, retention_justification, sensitivity_level,
  data_origin, data_controller_id, data_processor_id, data_steward_id,
  status, last_reviewed_at, next_review_date, created_by
) VALUES 
  (
    gen_random_uuid(),
    'Dados de Clientes - CRM Principal',
    'Base completa de dados de clientes no sistema CRM principal da empresa',
    'identificacao',
    ARRAY['nome', 'cpf', 'rg', 'email', 'telefone', 'endereco', 'data_nascimento'],
    'Sistema CRM Enterprise',
    'crm_production',
    ARRAY['customers.name', 'customers.document', 'customers.email', 'addresses.full_address'],
    ARRAY['/data/crm/customer_files/', '/backup/crm_daily/'],
    250000,
    60,
    'Retenção necessária para manutenção do relacionamento comercial e cumprimento de obrigações contratuais',
    'alta',
    'coleta_direta',
    (SELECT id FROM auth.users LIMIT 1),
    NULL,
    (SELECT id FROM auth.users LIMIT 1),
    'active',
    NOW() - INTERVAL '15 days',
    NOW() + INTERVAL '6 months',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Dados de Funcionários - RH',
    'Dados pessoais e profissionais dos funcionários para gestão de recursos humanos',
    'profissional',
    ARRAY['nome', 'cpf', 'conta_bancaria', 'telefone', 'endereco'],
    'Sistema de RH (TOTVS)',
    'hr_system',
    ARRAY['employees.personal_data', 'employees.bank_info', 'payroll.salary_data'],
    ARRAY['/hr/employee_docs/', '/hr/contracts/'],
    1500,
    120,
    'Dados mantidos por 10 anos após desligamento conforme legislação trabalhista',
    'critica',
    'coleta_direta',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1),
    'active',
    NOW() - INTERVAL '30 days',
    NOW() + INTERVAL '12 months',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Logs de Acesso - Segurança',
    'Registros de acesso aos sistemas e instalações físicas',
    'comportamental',
    ARRAY['localizacao_gps', 'biometria', 'historico_compras'],
    'Sistema de Segurança Integrado',
    'security_logs',
    ARRAY['access_logs.user_id', 'access_logs.location', 'access_logs.timestamp'],
    ARRAY['/security/access_logs/', '/security/camera_footage/'],
    5000000,
    36,
    'Logs mantidos por 3 anos para investigações de segurança e auditoria',
    'media',
    'sistemas_internos',
    (SELECT id FROM auth.users LIMIT 1),
    NULL,
    (SELECT id FROM auth.users LIMIT 1),
    'active',
    NOW() - INTERVAL '45 days',
    NOW() + INTERVAL '6 months',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Dados Financeiros - Contabilidade',
    'Informações financeiras de clientes e transações para controle contábil',
    'financeiro',
    ARRAY['conta_bancaria', 'cartao_credito', 'historico_compras'],
    'Sistema Contábil (SAP)',
    'financial_db',
    ARRAY['transactions.amount', 'transactions.payment_method', 'invoices.customer_data'],
    ARRAY['/finance/invoices/', '/finance/receipts/'],
    750000,
    60,
    'Retenção por 5 anos conforme obrigações fiscais da Receita Federal',
    'critica',
    'coleta_direta',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1),
    'active',
    NOW() - INTERVAL '20 days',
    NOW() + INTERVAL '6 months',
    (SELECT id FROM auth.users LIMIT 1)
  );

-- Incidentes de Privacidade (cenários diversos)
INSERT INTO privacy_incidents (
  id, title, description, incident_type, severity_level,
  affected_data_categories, estimated_affected_individuals,
  discovered_at, discovered_by, occurred_at, contained_at,
  root_cause, incident_source, impact_description,
  financial_impact, reputational_impact, regulatory_impact_risk,
  containment_measures, investigation_findings, corrective_actions,
  internal_notification_sent, internal_notified_at,
  anpd_notification_required, anpd_notified, anpd_notification_date,
  anpd_response_received, anpd_response_date, anpd_reference_number,
  data_subjects_notification_required, data_subjects_notified,
  data_subjects_notification_date, notification_method,
  incident_manager_id, dpo_id, legal_team_notified, status, closed_at,
  created_by
) VALUES 
  (
    gen_random_uuid(),
    'Vazamento de Email por Configuração Incorreta',
    'Lista de emails de clientes foi exposta temporariamente devido a configuração incorreta no sistema de marketing',
    'data_breach',
    'medium',
    ARRAY['contato'],
    1250,
    NOW() - INTERVAL '5 days',
    'Analista de Segurança',
    NOW() - INTERVAL '7 days',
    NOW() - INTERVAL '4 days',
    'Configuração incorreta de permissões no sistema de CRM durante atualização',
    'Erro de configuração interna',
    'Exposição temporária de 1.250 endereços de email por aproximadamente 3 dias',
    0,
    'Baixo - exposição limitada apenas a emails',
    'Médio - possível notificação à ANPD devido ao número de titulares',
    ARRAY['Correção imediata da configuração', 'Auditoria completa de permissões', 'Bloqueio de acesso não autorizado'],
    'Falha humana durante processo de atualização - falta de verificação de permissões',
    ARRAY['Implementação de checklist obrigatório para atualizações', 'Treinamento adicional da equipe técnica', 'Revisão de procedimentos'],
    true,
    NOW() - INTERVAL '5 days',
    true,
    true,
    NOW() - INTERVAL '2 days',
    false,
    NULL,
    'ANPD-2024-001234',
    true,
    true,
    NOW() - INTERVAL '1 day',
    'email',
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1),
    true,
    'resolved',
    NOW() - INTERVAL '6 hours',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Acesso Não Autorizado por Ex-funcionário',
    'Ex-funcionário manteve acesso ao sistema após desligamento e acessou dados de clientes',
    'unauthorized_access',
    'high',
    ARRAY['identificacao', 'contato', 'financeiro'],
    500,
    NOW() - INTERVAL '2 days',
    'Auditoria Interna',
    NOW() - INTERVAL '15 days',
    NOW() - INTERVAL '1 day',
    'Falha no processo de desligamento - acesso não foi revogado adequadamente',
    'Falha de processo interno',
    'Acesso indevido a dados de 500 clientes incluindo informações pessoais e financeiras',
    5000,
    'Alto - acesso malicioso por ex-funcionário',
    'Alto - dados sensíveis acessados indevidamente',
    ARRAY['Revogação imediata de todos os acessos', 'Mudança de senhas de sistemas críticos', 'Revisão completa de permissões'],
    'Processo de offboarding inadequado - falta de automação na revogação de acessos',
    ARRAY['Implementação de sistema automatizado de revogação', 'Procedimento de verificação pós-desligamento', 'Auditoria mensal de acessos'],
    true,
    NOW() - INTERVAL '2 days',
    true,
    true,
    NOW() - INTERVAL '1 day',
    false,
    NULL,
    'ANPD-2024-001235',
    true,
    false,
    NULL,
    NULL,
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1),
    true,
    'investigating',
    NULL,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Malware em Estação de Trabalho',
    'Detecção de malware em computador do setor financeiro com potencial acesso a dados sensíveis',
    'malware',
    'critical',
    ARRAY['financeiro', 'identificacao'],
    2000,
    NOW() - INTERVAL '1 day',
    'Sistema Antivírus Automático',
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '18 hours',
    'Malware instalado via email de phishing direcionado',
    'Phishing direcionado',
    'Potencial comprometimento de dados financeiros de até 2.000 clientes',
    15000,
    'Crítico - possível exfiltração de dados financeiros',
    'Muito Alto - dados financeiros extremamente sensíveis',
    ARRAY['Isolamento imediato da estação infectada', 'Análise forense completa', 'Verificação de exfiltração de dados'],
    'Análise forense em andamento - ainda não identificada exfiltração',
    ARRAY['Reforço do treinamento anti-phishing', 'Implementação de sandbox para emails', 'Monitoramento avançado de rede'],
    true,
    NOW() - INTERVAL '1 day',
    true,
    false,
    NULL,
    false,
    NULL,
    NULL,
    true,
    false,
    NULL,
    NULL,
    (SELECT id FROM auth.users LIMIT 1),
    (SELECT id FROM auth.users LIMIT 1),
    true,
    'investigating',
    NULL,
    (SELECT id FROM auth.users LIMIT 1)
  );

-- DPIAs (Avaliações de Impacto)
INSERT INTO dpia_assessments (
  id, title, description, processing_activity_id,
  involves_high_risk, involves_sensitive_data, involves_large_scale,
  involves_profiling, involves_automated_decisions, involves_vulnerable_individuals,
  involves_new_technology, dpia_required, dpia_justification,
  privacy_risks, risk_level, likelihood_assessment, impact_assessment,
  mitigation_measures, residual_risk_level, anpd_consultation_required,
  anpd_consultation_date, anpd_response_date, anpd_recommendation,
  conducted_by, reviewed_by, approved_by, dpo_id, status,
  started_at, completed_at, approved_at, created_by
) VALUES 
  (
    gen_random_uuid(),
    'DPIA - Sistema de Análise Comportamental de Clientes',
    'Avaliação de impacto para implementação de sistema de análise comportamental para personalização de ofertas',
    NULL,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    'Sistema envolve processamento automatizado de dados comportamentais em larga escala com potencial impacto significativo nos direitos dos titulares',
    ARRAY[
      'Perfilização automática baseada em comportamento de compra',
      'Possível discriminação em ofertas baseada em perfil socioeconômico',
      'Coleta excessiva de dados comportamentais',
      'Decisões automatizadas sem revisão humana'
    ],
    'high',
    4,
    4,
    ARRAY[
      'Implementação de opt-in explícito para análise comportamental',
      'Revisão humana obrigatória para decisões de alto impacto',
      'Limitação de dados coletados ao mínimo necessário',
      'Implementação de direito à explicação para decisões automatizadas',
      'Auditoria algorítmica regular'
    ],
    'medium',
    false,
    NULL,
    NULL,
    NULL,
    'DPO da Empresa',
    'Comitê de Privacidade',
    'Diretoria Executiva',
    (SELECT id FROM auth.users LIMIT 1),
    'approved',
    NOW() - INTERVAL '45 days',
    NOW() - INTERVAL '15 days',
    NOW() - INTERVAL '10 days',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'DPIA - Videomonitoramento com Reconhecimento Facial',
    'Avaliação para implementação de sistema de videomonitoramento com tecnologia de reconhecimento facial',
    NULL,
    true,
    true,
    false,
    true,
    true,
    false,
    true,
    true,
    'Reconhecimento facial constitui tratamento de dados biométricos com alto risco para privacidade',
    ARRAY[
      'Processamento de dados biométricos (reconhecimento facial)',
      'Monitoramento contínuo de pessoas',
      'Potencial para vigilância excessiva',
      'Risco de falsos positivos/negativos',
      'Possível uso indevido dos dados biométricos'
    ],
    'very_high',
    5,
    5,
    ARRAY[
      'Consulta obrigatória à ANPD antes da implementação',
      'Consentimento específico para dados biométricos',
      'Limitação do reconhecimento facial apenas para áreas críticas',
      'Retenção mínima de dados biométricos',
      'Criptografia avançada para dados biométricos'
    ],
    'high',
    true,
    NOW() - INTERVAL '30 days',
    NOW() - INTERVAL '15 days',
    'ANPD recomenda implementação gradual com medidas de segurança reforçadas e revisão após 6 meses',
    'DPO da Empresa',
    'Consultoria Externa de Privacidade',
    NULL,
    (SELECT id FROM auth.users LIMIT 1),
    'pending_approval',
    NOW() - INTERVAL '60 days',
    NOW() - INTERVAL '20 days',
    NULL,
    (SELECT id FROM auth.users LIMIT 1)
  );

-- Atividades de Tratamento (para completar o RAT)
INSERT INTO processing_activities (
  id, name, description, purpose, data_categories, data_types,
  data_subjects_categories, legal_basis_id, legal_basis_justification,
  data_controller_name, data_controller_contact, data_processor_name,
  data_processor_contact, data_sharing_third_parties, international_transfer,
  international_transfer_countries, international_transfer_safeguards,
  retention_period_months, retention_criteria, deletion_procedure,
  security_measures, technical_measures, organizational_measures,
  data_protection_officer_id, responsible_area, responsible_person_id,
  status, last_reviewed_at, next_review_date, created_by
) VALUES 
  (
    gen_random_uuid(),
    'Gestão de Relacionamento com Clientes',
    'Tratamento de dados pessoais para gestão completa do relacionamento comercial com clientes',
    'Manutenção e gestão do relacionamento comercial, incluindo atendimento, suporte e ofertas personalizadas',
    ARRAY['identificacao', 'contato', 'financeiro', 'comportamental'],
    ARRAY['nome', 'email', 'telefone', 'cpf', 'endereco', 'historico_compras', 'preferencias'],
    ARRAY['clientes_ativos', 'prospects', 'ex_clientes'],
    (SELECT id FROM legal_bases WHERE legal_basis_type = 'contrato' LIMIT 1),
    'Execução de contrato do qual o titular é parte ou diligências pré-contratuais',
    'Empresa XYZ Ltda',
    'privacidade@empresa.com.br',
    NULL,
    NULL,
    ARRAY['Empresa de Logística ABC', 'Gateway de Pagamento DEF'],
    false,
    NULL,
    NULL,
    60,
    'Dados mantidos enquanto houver relacionamento comercial ativo + 5 anos para fins fiscais',
    'Anonimização seguida de exclusão física dos sistemas após período de retenção',
    ARRAY['Criptografia em trânsito e em repouso', 'Controle de acesso baseado em função', 'Auditoria de acessos'],
    'TLS 1.3, AES-256, Autenticação multifator',
    'Treinamento de conscientização, Políticas de segurança, Contratos de confidencialidade',
    (SELECT id FROM auth.users LIMIT 1),
    'Comercial e Marketing',
    (SELECT id FROM auth.users LIMIT 1),
    'active',
    NOW() - INTERVAL '60 days',
    NOW() + INTERVAL '12 months',
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    'Gestão de Recursos Humanos',
    'Tratamento de dados pessoais de funcionários para gestão de RH, folha de pagamento e obrigações trabalhistas',
    'Gestão completa de recursos humanos incluindo contratação, desenvolvimento, pagamento e cumprimento de obrigações legais',
    ARRAY['identificacao', 'contato', 'profissional', 'financeiro', 'saude'],
    ARRAY['nome', 'cpf', 'rg', 'endereco', 'telefone', 'email', 'conta_bancaria', 'historico_medico'],
    ARRAY['funcionarios_ativos', 'funcionarios_afastados', 'ex_funcionarios'],
    (SELECT id FROM legal_bases WHERE legal_basis_type = 'contrato' LIMIT 1),
    'Execução de contrato de trabalho e cumprimento de obrigações legais trabalhistas',
    'Empresa XYZ Ltda',
    'rh@empresa.com.br',
    'Folha de Pagamento S/A',
    'contato@folhapagamento.com.br',
    ARRAY['INSS', 'Receita Federal', 'Plano de Saúde'],
    false,
    NULL,
    NULL,
    120,
    'Dados mantidos durante vínculo empregatício + 10 anos após desligamento conforme legislação trabalhista',
    'Arquivamento em sistema de guarda legal seguido de destruição física após prazo legal',
    ARRAY['Controle de acesso restrito ao RH', 'Criptografia de dados sensíveis', 'Backup seguro'],
    'Certificado digital A3, Criptografia AES-256, VPN para acesso remoto',
    'Treinamento específico para equipe de RH, Segregação de funções, Monitoramento de acessos',
    (SELECT id FROM auth.users LIMIT 1),
    'Recursos Humanos',
    (SELECT id FROM auth.users LIMIT 1),
    'active',
    NOW() - INTERVAL '90 days',
    NOW() + INTERVAL '12 months',
    (SELECT id FROM auth.users LIMIT 1)
  );

-- Comunicações com ANPD
INSERT INTO anpd_communications (
  id, incident_id, communication_type, reference_number, sent_date,
  response_received_date, anpd_response, follow_up_required,
  follow_up_date, status, documents_sent, created_by
) VALUES 
  (
    gen_random_uuid(),
    (SELECT id FROM privacy_incidents WHERE title LIKE '%Email%' LIMIT 1),
    'incident_notification',
    'ANPD-2024-001234',
    NOW() - INTERVAL '2 days',
    NULL,
    NULL,
    true,
    NOW() + INTERVAL '5 days',
    'sent',
    ARRAY['incident-report.pdf', 'technical-analysis.pdf', 'containment-measures.pdf'],
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    gen_random_uuid(),
    (SELECT id FROM privacy_incidents WHERE title LIKE '%Ex-funcionário%' LIMIT 1),
    'incident_notification',
    'ANPD-2024-001235',
    NOW() - INTERVAL '1 day',
    NULL,
    NULL,
    true,
    NOW() + INTERVAL '4 days',
    'sent',
    ARRAY['unauthorized-access-report.pdf', 'forensic-analysis.pdf'],
    (SELECT id FROM auth.users LIMIT 1)
  );

-- Atualizar estatísticas das tabelas
ANALYZE legal_bases;
ANALYZE consents;
ANALYZE data_subject_requests;
ANALYZE data_inventory;
ANALYZE privacy_incidents;
ANALYZE dpia_assessments;
ANALYZE processing_activities;
ANALYZE anpd_communications;

-- Confirmar sucesso da inserção
SELECT 
  'Dados de teste carregados com sucesso!' as message,
  (SELECT COUNT(*) FROM legal_bases) as legal_bases,
  (SELECT COUNT(*) FROM consents) as consents,
  (SELECT COUNT(*) FROM data_subject_requests) as data_subject_requests,
  (SELECT COUNT(*) FROM data_inventory) as data_inventory,
  (SELECT COUNT(*) FROM privacy_incidents) as privacy_incidents,
  (SELECT COUNT(*) FROM dpia_assessments) as dpia_assessments,
  (SELECT COUNT(*) FROM processing_activities) as processing_activities,
  (SELECT COUNT(*) FROM anpd_communications) as anpd_communications;