CREATE TABLE IF NOT EXISTS vulnerabilities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    severity VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Open',
    cvss_score DECIMAL(3,1),
    cve_id VARCHAR(50),
    asset_name VARCHAR(255) NOT NULL,
    asset_ip INET,
    source_tool VARCHAR(100) NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    port INTEGER,
    protocol VARCHAR(20),
    first_found_date TIMESTAMP WITH TIME ZONE,
    last_found_date TIMESTAMP WITH TIME ZONE,
    solution TEXT,
    references TEXT[],
    assigned_to VARCHAR(255),
    due_date TIMESTAMP WITH TIME ZONE,
    sla_breach BOOLEAN DEFAULT FALSE,
    raw_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID,
    updated_by UUID
);