// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types'; // disabled: types file is empty to avoid TS issues

// Configuração para Supabase REMOTO (produção) - ATIVO
const SUPABASE_URL = "https://myxvxponlmulnjstbjwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15eHZ4cG9ubG11bG5qc3RiandkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTQzNTMsImV4cCI6MjA2ODU5MDM1M30.V9yqc2cgrRCLxlXF2HkISzPT9WQ7Hw14r_yE8UROgD4";

// Configuração para Supabase LOCAL (desenvolvimento) - comentado
// const SUPABASE_URL = "http://localhost:54321";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// NOTA: Usando Supabase REMOTO para produção

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detectar se esta aba é uma sessão de impersonação
// Se for, o cliente principal NÃO deve capturar o #access_token do magic link
// (isso será feito exclusivamente pelo createImpersonationClient)
const isImpersonationTab = typeof window !== 'undefined' &&
  new URLSearchParams(window.location.search).get('impersonated') === 'true';

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !isImpersonationTab, // não captura magic link em aba de impersonação
  }
});

// Cliente isolado por sessionStorage para uso em abas de impersonação.
// Cada aba tem seu próprio sessionStorage — a sessão do usuário impersonado
// fica separada da sessão do admin (que usa localStorage).
export const createImpersonationClient = () =>
  createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: sessionStorage,
      storageKey: 'grc-impersonation-session',
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,   // processa o #access_token do magic link
    }
  });

export { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
